name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        wget https://github.com/JetBrains/kotlin/releases/download/v1.4.10/kotlin-native-linux-1.4.10.tar.gz
        tar xzvf kotlin-native-linux-1.4.10.tar.gz
    - name: compile
      run: |
        kotlin-native-linux-1.4.10/bin/kotlinc-native hello.kt -o hello
    - name: run
      run: |
        ./hello.kexe
    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /home/runner/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
